### PR TITLE
[Merged by Bors] - krb5: Remove dummy key from keytab

### LINKED ISSUE #283: Remove dummy principal from KRB5 keytabs
This is breaking `kinit -ki`, which is otherwise a useful way for administrators to get a ticket.

### PR DESCRIPTION
**Pull request by nightkr**
# Description

Fixes #283.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by sbernauer** [comment]
I'm running into `thread 'main' panicked at 'no gssapi implementation found, install mit kerberos or heimdal', build.rs:47:9`
```
$ apt search libgssapi
Sorting... Done
Full Text Search... Done
libgssapi-krb5-2/jammy-updates,now 1.19.2-2ubuntu0.2 amd64 [installed,automatic]
  MIT Kerberos runtime libraries - krb5 GSS-API Mechanism

libgssapi-perl/jammy 0.28-3build5 amd64
  Perl extension providing access to the GSSAPIv2 library

libgssapi3-heimdal/jammy 7.7.0+dfsg-3ubuntu1 amd64
  Heimdal Kerberos - GSSAPI support library
```
Is there something I am missing or maybe does the detection not work?

**Comment by nightkr** [comment]
I assume you're building with `cargo build`? I recently ran into the same thing (279a413f2c0e78ae27e8adb097e1012b3c915a26), something seems to have got stricter recently...

I think on Ubuntu you'll need to install `libkrb5-3` and maybe `libkrb5-dev`, but those should already be pulled in like that...

**Review by sbernauer — APPROVED** [review]
Many thanks!

**Pull request closed without merging**
