### PR TITLE
[Merged by Bors] - Remove `secretLabels` option from `k8sSearch` backend

### PR DESCRIPTION
**Pull request by teozkr**
## Description

This never had any real purpose, since we always add the name of the `SecretClass` as a required label anyway.

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by sbernauer — APPROVED** [review]
LGTM.
Out of curiosity: What's the reason for removing the label selector?

**Comment by sbernauer** [comment]
Did you check that no examples for products or integration-tests use this attribute?

**Comment by teozkr** [comment]
>  Out of curiosity: What's the reason for removing the label selector?

It's completely redundant, since the name of the secretclass must be specified on the secrets anyway, preventing any kind of overlap.

> Did you check that no examples for products or integration-tests use this attribute?

I looked through the secret-op repo itself, but haven't searched downstream.

**Comment by teozkr** [comment]
https://github.com/search?q=org%3Astackabletech+secretLabels&type=code only finds matches within the secret-op repo itself.

**Comment by sbernauer** [comment]
Thanks a lot!

**Pull request closed without merging**
