### PR TITLE
docs: Secret Operator installation guide link updated

### PR DESCRIPTION
**Pull request by Pscheidl**
## Review Checklist

- [x] Code contains useful comments
- [x] CRD change approved (or not applicable)
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by soenkeliebau — APPROVED** [review]
Good catch, thanks!

**Review by soenkeliebau — CHANGES_REQUESTED** [review]
Hi @Pscheidl thanks for catching this!
I missed a small thing in my initial review, which is that the README actually get generated in our operators. 
We do test for this in our ci, which reminded me of this fact :)

You also need to correct the link at this position: https://github.com/stackabletech/secret-operator/blob/ed97fb3b90429420a8639755a8e1fa1d345455d2/.readme/partials/main.md.j2#L7

Happy to do so myself, but wanted to talk to you first..

**Comment by Pscheidl** [comment]
I'll do it. I just need to get back to my laptop, could take a few hours.

**Comment by Pscheidl** [comment]
There we go, let's see what Mr. Bors has to say. :wink:

**Comment by soenkeliebau** [comment]
CI failure is due to this PR being opened from a fork and not getting access to push secrets. This step should have been bypassed in CI, will investigate separately, but merge this for now.

**Pull request merged**
