### PR TITLE
[Merged by Bors] - Update documentation on how to build and run

### PR DESCRIPTION
**Pull request by teozkr**
## Description

This was wildly outdated, as noted by @lfrancke. There's still some work to be done aligning the build modes, but at least this ensures that the docs are aligned with the current reality.

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by razvan — COMMENTED** [review]
Maybe also add a word about using git sub-modules. It wasn't obvious to me what was missing when trying to build the operator.

**Comment by teozkr** [comment]
Good point.

**Review by razvan — APPROVED** [review]
Successfully ran the installation steps with docker and kind.

**Comment by lfrancke** [comment]
Thank you for picking up this review @razvan !

**Pull request closed without merging**
