### PR TITLE
Give RBAC permission to read listeners

### PR DESCRIPTION
**Pull request by nightkr**
# Description

This is required for listener volume scopes that use manually created listeners

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

### CODE REVIEW

**Review by sbernauer — APPROVED** [review]

**Comment by nightkr** [comment]
I'd say no, unless you want to list every bugfix (and at that point, what's the difference vs the changelog again?).

**Comment by lfrancke** [comment]
It's a subjective thing. I thought this might warrant an entry because it's security relevant and should someone not use our Helm charts for some reason, they'd need to take action.

Also....do we need to do anything for OpenShift here @razvan @adwk67?

**Comment by razvan** [comment]
Yes, we need to to check for this when updating OLM

**Comment by lfrancke** [comment]
Do we have an issue or anything else to track this so we don't forget? If not: Do we need it?

**Comment by razvan** [comment]
I'd say we don't need an issue for it. Diffing cluster roles between Helm and OLM is part of the process. Also the OpenShift tests will hopefully catch any inconsistencies.

**Comment by nightkr** [comment]
Well if you want to add a release note for it, something like:

> The Stackable Secret Operator now requests permission to read Listeners, which is required to provision secrets for listener volumes with `listeners.stackable.tech/listener-name`.

**Pull request merged**
