### PR TITLE
Make CA lifetimes configurable

### LINKED ISSUE #354: Allow configuring CA cert lifetime and refresh interval
Extracted from https://github.com/stackabletech/secret-operator/pull/350#discussion_r1469442628

This might be a breaking change for https://github.com/stackabletech/issues/issues/504

### PR DESCRIPTION
**Pull request by nightkr**
# Description

Fixes #354

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [x] Code contains useful comments
- [ ] (Integration-)Test cases added
- [x] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by fhennig — CHANGES_REQUESTED** [review]
Can you add some docs to this page? https://docs.stackable.tech/home/nightly/secret-operator/secretclass#backend-autotls

_maybe_ the property could be `lifetime` instead of `caLifetime` since it's under the `ca` key already (sorry for the bikeshedding :grimacing: )

other than that, looks good to me :+1:

**Comment by nightkr** [comment]
Added docs, updated to align with the CRD review.

**Review by fhennig — APPROVED** [review]
Looks good to me.

regarding the 2y default in `default_ca_certificate_lifetime` I think it might be easiest to update it in here still. I can re-approve if you sitll want to change this @nightkr

**Comment by sbernauer** [comment]
The ticket we discussed in Arch meeting is https://github.com/stackabletech/secret-operator/issues/358 ;)

**Comment by fhennig** [comment]
Alright so yeah fine either way, do it here and close #358 too or not :ok:

**Comment by nightkr** [comment]
I think either is fine, I'd personally do it in a separate PR and changelog entry.

**Review by fhennig — CHANGES_REQUESTED** [review]
```
error: unresolved link to `Self::ca_lifetime`
   --> rust/operator-binary/src/backend/tls/ca.rs:154:28
    |
154 |     /// and smaller than [`Self::ca_lifetime`].
    |                            ^^^^^^^^^^^^^^^^^ the struct `Config` has no field or associated item named `ca_lifetime`
    |
    = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(rustdoc::broken_intra_doc_links)]`

error: could not document `stackable-secret-operator`
```

**Comment by nightkr** [comment]
Argh, you're right. Should be fixed now..

**Review by fhennig — APPROVED** [review]
LGTM!

**Pull request merged**
