### PR TITLE
[Merged by Bors] - Run secret-operator as root when deployed by Helm

### PR DESCRIPTION
**Pull request by teozkr**
## Description

This seems to have been another value accidentally removed by the templating scripts

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by teozkr** [comment]
Helm installs seem to work again once this PR is merged.

**Review by soenkeliebau — APPROVED** [review]

**Comment by teozkr** [comment]
bors r-

Oh, of course I forget to update the manifests.. lol

**Pull request closed without merging**
